pipeline {
    agent { label 'docker-slave' }
    tools {
        maven 'maven'
        java 'jdk8'
    }

    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}