pipeline {
    agent { label 'docker-slave' }
    tools {
        maven 'maven'
    }

    environment {
        JAVA_HOME = "/usr/local/openjdk-8"
        PATH = "$PATH:/usr/local/bin:/usr/local/openjdk-8/bin"
    }

    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}